id: I068E8C92
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T06:04:51+00:00'
last_modified: '2022-06-08T08:14:45.001958+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC229
  title: སྡེ་བདུན་རྒྱ་མཚོར་འཇུག་པའི་གྲུ་གཟིངས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6324':
      image_group_id: I2PD17770
      title: ''
      total_pages: 518
      order: 1
      base_file: 6324.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
